name: Build and Push Docker Image to Docker Hub (on merge to staging)

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'skip-ci'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Image Tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/k8s-full-working-design-backend:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-full-working-design-backend:${{ env.IMAGE_TAG }}

      - name: Optional - Tag as latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/k8s-full-working-design-backend:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/k8s-full-working-design-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-full-working-design-backend:latest
